# Generated by Django 6.0.1 on 2026-02-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobapplication_email_jobapplication_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
